samples: samples.tsv

files_path:
    genome_reg: /array2/genomes/hg38.ensGene.gtf
    genome_fa: /array2/pedrobarros/genomes/hg38.fa
    transcript_fa: /array2/pedrobarros/genomes/hg38.ensGene.fa

params:
    stranded: yes
    read_len: 150

    # Expression parameters
    expFDR_threshold: 0.05
    foldChange_threshold: 1
    # Alternative splicing parameters
    AS_FDR_threshold: 0.05
    AS_incLevel_threshold: 0.1
    # RNA editing parameters
    RED_FDR_threshold: 0.05
